name: Build and push release image

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }} # ghcr.io/owner/repo
  DOCKERFILE: ./deployments/Dockerfile
  CONTEXT: .

concurrency:
  group: docker-release
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v5

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE }}
        tags: |
          # リリースタグと同名（例: v1.2.3 → v1.2.3）
          type=semver,pattern={{version}}
          # セマンティックバージョンの浮動タグ（例: v1.2.3 → 1.2, 1）
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
      # TODO: add latest tag when release is a full release

    - uses: docker/build-push-action@v6
      with:
        context: ${{ env.CONTEXT }}
        file: ${{ env.DOCKERFILE }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
