name: Build and push dev image
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }} # ghcr.io/owner/repo
  DOCKERFILE: ./deployments/Dockerfile
  CONTEXT: .

concurrency:
  group: docker-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  
    steps:
    - uses: actions/checkout@v5

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE }}
        tags: |
          type=raw,value=dev
          type=sha

    - uses: docker/build-push-action@v6
      with:
        context: ${{ env.CONTEXT }}
        file: ${{ env.DOCKERFILE }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
